---
# tasks file for ansible-cisco_ios_upgrade
#
# ██╗ ██████╗ ███████╗   ██╗  ██╗       ██╗   ██╗███████╗██████╗ ██╗███████╗██╗███╗   ██╗ ██████╗ 
# ██║██╔═══██╗██╔════╝   ██║  ██║       ██║   ██║██╔════╝██╔══██╗██║██╔════╝██║████╗  ██║██╔════╝ 
# ██║██║   ██║███████╗   ███████║       ██║   ██║█████╗  ██████╔╝██║█████╗  ██║██╔██╗ ██║██║  ███╗
# ██║██║   ██║╚════██║   ╚════██║       ╚██╗ ██╔╝██╔══╝  ██╔══██╗██║██╔══╝  ██║██║╚██╗██║██║   ██║
# ██║╚██████╔╝███████║███████╗██║███████╗╚████╔╝ ███████╗██║  ██║██║██║     ██║██║ ╚████║╚██████╔╝
# ╚═╝ ╚═════╝ ╚══════╝╚══════╝╚═╝╚══════╝ ╚═══╝  ╚══════╝╚═╝  ╚═╝╚═╝╚═╝     ╚═╝╚═╝  ╚═══╝ ╚═════╝ 
# 

- name: ios_4_verifying | Define section
  ansible.builtin.set_fact:
    section: "ios_4_verifying"
  tags:
    - verifying

#------------------------------------------------------------------------------
# Image exist on device filesystem
#------------------------------------------------------------------------------
- name: ios_4_verifying | IOS image found
  ansible.builtin.assert:
    that:
      - found_required_file
    fail_msg: "The required IOS image couldn't be found on device filesystem."
    success_msg: "The required IOS image exist on device filesystem."
  tags:
    - verifying

#------------------------------------------------------------------------------
# Required IOS image found on device filesystem
#------------------------------------------------------------------------------
- name: ios_4_verifying
  when: found_required_file 
  block:

    #--------------------------------------------------------------------------
    # Validate if variable 'use_signature' is defined and set with the string
    # 'MD5' or 'SHA512'.
    #--------------------------------------------------------------------------
    - name: ios_4_verifying | Validate use_signature
      ansible.builtin.assert:
        that:
          - "use_signature|upper == 'MD5' or use_signature|upper == 'SHA512'"
          - "use_signature is defined"
        fail_msg: "The variable use_signature isn't defined or doesn't have the 
                  the string MD5 or SHA512."

    #--------------------------------------------------------------------------
    # Use command: verify /(<md5>|<sha512>) flash:<image directory>/<image name>
    #--------------------------------------------------------------------------
    - name: ios_4_verifying | Compute an MD5 or SHA512 signature for a file
      vars:
        ansible_command_timeout: 900
      register: hash_result
      cisco.ios.ios_command:
        commands: "verify 
          {{ 
            '/md5' 
              if (use_signature|upper == 'MD5') 
              else 
                ( 
                  '/sha512' 
                    if (use_signature|upper == 'SHA512') 
                    else '' 
                ) 
          }} {{ filesystem }}{{ required_ios_binary[:-4] }}/{{ required_ios_binary }}"
      loop_control:
        loop_var: filesystem
      with_items: "{{ device_filesystem_info.keys() | list }}"

    #--------------------------------------------------------------------------
    # If the string behind the variable 'required_ios_md5' or 
    # 'required_ios_sha512' matches with the output of the running command
    # verify then set the flag True into the list else False.
    #--------------------------------------------------------------------------
    - name: ios_4_verifying | Validate checksum
      set_fact:
        checksum_match: "{{ ( checksum_match|default([]) ) +  
            [ 
              (
                True
                  if (required_ios_md5 in item.stdout[0])
                  else False
              )
                if (use_signature|upper == 'MD5')
                else 
                (
                  True
                    if (required_ios_sha512 in item.stdout[0])
                    else False
                )
            ] }}"
      with_items: "{{ hash_result.results }}"

    #--------------------------------------------------------------------------
    # example stacked device with 2 members:
    # checksum_match = [ 'True' , 'False' ]
    # which means that one member doesn't match the checksum test.
    #--------------------------------------------------------------------------
    - name: ios_4_verifying | Debug
      when: debug_all or debug_ios
      ansible.builtin.debug: var=checksum_match

    #--------------------------------------------------------------------------
    # If the list contians the boolean False then to remove the IOS directory
    # on all member filesystems.
    #--------------------------------------------------------------------------
    - name: ios_4_verifying | Verification failed on device - delete IOS images
      when:
        - False in checksum_match
      cisco.ios.ios_command:
        commands: "delete /force /recursive {{ filesystem }}{{ required_ios_binary[:-4] }}"
      loop_control:
        loop_var: filesystem
      with_items: "{{ device_filesystem_info.keys() | list }}"
      
    - name: ios_4_staging | Validate when checksums are identical
      ansible.builtin.assert:
        that: 
          - False not in checksum_match
        fail_msg: "Mismatch during validation of checksums"
        success_msg: "Checksum verification was successfully"

  tags:
    - verifying

#------------------------------------------------------------------------------
# Define the next step
#------------------------------------------------------------------------------
- name: ios_4_verifying | Next step
  ansible.builtin.set_fact:
    ios_next_step: "booting"

#                       _ _   
#   _ __ ___  ___ _   _| | |_ 
#  | '__/ _ \/ __| | | | | __|
#  | | |  __/\__ \ |_| | | |_ 
#  |_|  \___||___/\__,_|_|\__|
#
#------------------------------------------------------------------------------
# Display result status
#------------------------------------------------------------------------------
- name: ios_4_verifying | Results
  ansible.builtin.debug:
    msg:
      - "{{
          (
            'Next step is ' + ios_next_step
          ) if
            (
              not using_tag
            ) 
          else 
            (
              (
                'Ending of tag verifying.'
              ) if 
                  (
                    ios_next_step|lower == 'verifying'
                  )
                else 
                  ( 
                    'Next step is ' + ios_next_step 
                  )
            )
        }}"
  tags:
    - verifying
